# Generated by Django 4.2.7 on 2024-03-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0002_remove_movie_subgenre_genre_movies_subgenre_movies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
