# Generated by Django 4.2.7 on 2024-03-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0003_movie_youtube_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
