# Generated by Django 4.2.7 on 2024-03-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0004_alter_movie_youtube_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.CharField(choices=[('U', 'U - Universal (suitable for all)'), ('UA', 'UA - Universal with Adult (parental guidance required for children under 12)'), ('A', 'A - Adults Only'), ('S', 'S - Special (restricted to specific audiences)'), ('Unrated', 'Unrated')], default='Unrated', max_length=10),
        ),
    ]
